### ISSUE TITLE
Shadowing class BufferUtils: get it to work

### ISSUE THREAD

**Issue by keesvandieren** [squins/gdx-backend-bytecoder#5]
Libgdx has a native class: com.badlogic.gdx.utils.BufferUtils

We have to emulate it. We try to follow: https://mirkosertic.github.io/Bytecoder/chapter-1/page-1-g/#emulating-classes-and-methods

We've added the class de.mirkosertic.bytecoder.classlib.com.badlogic.gdx.utils.TBufferUtils in our project, but it is not picked up.

Seems we have to add a Service Loader in META-INF/services.

That one is not picked up in our project.

So we have now added it in our Bytecoder fork (branch: classlib-gdx-in-bytecoder), in classlib/gdx, and then use that.

However that also is not working properly. It gives us the error:

```
Exception in thread "main" java.util.ServiceConfigurationError: de.mirkosertic.bytecoder.api.ClassLibProvider: Provider de.mirkosertic.bytecoder.classlib.GdxClassLibProvider not found
```

We are using JDK 1.8.

Steps to reproduce:

Step 1. clone and build squins Bytecoder clone

* clone https://github.com/squins/Bytecoder
* checkout branch: classlib-gdx-in-bytecoder
* build it into local repository (mvn install -DskipTests)

Step 2: clone and build libgdx-wasm-with-bytecoder

* clone https://github.com/squins/libgdx-wasm-with-bytecoder
* checkout branch  classlib-gdx-in-bytecoder
* run mvn install 

Error then shows up:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for gdx-backend-bytecoder-parent 1.0-SNAPSHOT:
[INFO] 
[INFO] gdx-backend-bytecoder-parent ....................... SUCCESS [  0.246 s]
[INFO] gdx-backend-bytecoder .............................. SUCCESS [  7.914 s]
[INFO] gdx-backend-bytecoder-example ...................... FAILURE [  1.733 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.043 s
[INFO] Finished at: 2020-10-21T08:11:34+02:00
[INFO] ------------------------------------------------------------------------
---------------------------------------------------
constituent[0]: file:/usr/local/Cellar/maven/3.6.3/libexec/conf/logging/
constituent[1]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/maven-plugin-api-3.6.3.jar
constituent[2]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/maven-compat-3.6.3.jar
constituent[3]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/maven-resolver-util-1.4.1.jar
constituent[4]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/plexus-component-annotations-2.1.0.jar
constituent[5]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/maven-settings-builder-3.6.3.jar
constituent[6]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/plexus-cipher-1.7.jar
constituent[7]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/plexus-interpolation-1.25.jar
constituent[8]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/maven-resolver-spi-1.4.1.jar
constituent[9]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/guice-4.2.1-no_aop.jar
constituent[10]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/maven-artifact-3.6.3.jar
constituent[11]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/maven-resolver-provider-3.6.3.jar
constituent[12]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/cdi-api-1.0.jar
constituent[13]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/maven-slf4j-provider-3.6.3.jar
constituent[14]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/plexus-utils-3.2.1.jar
constituent[15]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/plexus-sec-dispatcher-1.4.jar
constituent[16]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/maven-repository-metadata-3.6.3.jar
constituent[17]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/commons-cli-1.4.jar
constituent[18]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/maven-resolver-transport-wagon-1.4.1.jar
constituent[19]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/commons-io-2.5.jar
constituent[20]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/jansi-1.17.1.jar
constituent[21]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/maven-model-builder-3.6.3.jar
constituent[22]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/maven-embedder-3.6.3.jar
constituent[23]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/wagon-file-3.3.4.jar
constituent[24]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/org.eclipse.sisu.inject-0.3.4.jar
constituent[25]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/maven-resolver-connector-basic-1.4.1.jar
constituent[26]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/maven-settings-3.6.3.jar
constituent[27]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/maven-model-3.6.3.jar
constituent[28]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/maven-resolver-api-1.4.1.jar
constituent[29]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/jcl-over-slf4j-1.7.29.jar
constituent[30]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/wagon-http-3.3.4-shaded.jar
constituent[31]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/org.eclipse.sisu.plexus-0.3.4.jar
constituent[32]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/slf4j-api-1.7.29.jar
constituent[33]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/maven-builder-support-3.6.3.jar
constituent[34]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/jsoup-1.12.1.jar
constituent[35]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/wagon-provider-api-3.3.4.jar
constituent[36]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/maven-shared-utils-3.2.1.jar
constituent[37]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/maven-resolver-impl-1.4.1.jar
constituent[38]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/maven-core-3.6.3.jar
constituent[39]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/javax.inject-1.jar
constituent[40]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/commons-lang3-3.8.1.jar
constituent[41]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/guava-25.1-android.jar
constituent[42]: file:/usr/local/Cellar/maven/3.6.3/libexec/lib/jsr250-api-1.0.jar
---------------------------------------------------
Exception in thread "main" java.util.ServiceConfigurationError: de.mirkosertic.bytecoder.api.ClassLibProvider: Provider de.mirkosertic.bytecoder.classlib.GdxClassLibProvider not found
        at java.util.ServiceLoader.fail(ServiceLoader.java:239)
        at java.util.ServiceLoader.access$300(ServiceLoader.java:185)

```

**Comment by keesvandieren** [comment]
` mvn install -DskipTests` on bytecoder also fails with this message:

```
Exception in thread "main" java.util.ServiceConfigurationError: de.mirkosertic.bytecoder.api.ClassLibProvider: Provider de.mirkosertic.bytecoder.classlib.GdxClassLibProvider not found
```

Maybe it has to do with us not having src/main/resources/META-INF/modules? But we don't have any content for that as well.

**Comment by keesvandieren** [comment]
@CoenRijsdijk  / @tommyettinger FYI

**Comment by keesvandieren** [comment]
That problem was minor mistake, however TBufferUtils somehow still does not get processed

**Comment by keesvandieren** [comment]
Shadowing classes implemented successfully with Maven
